### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by Taka41802** [Taka41802/protospace-41802#1]
https://protospace-41802.onrender.com

**Comment by motomuun** [comment]
ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
**ユーザー管理機能**

- [x] **ログイン状態では、トップページに「こんにちは、〇〇さん」とユーザー名が表示されていること**
「さん」まで表示されるように修正しましょう。

**コメント機能**

- [x] **コメントフォームを空のまま投稿しようとすると、投稿できずにプロトタイプ詳細ページに戻ること**
コメントフォームを空のまま「送信する」ボタンを押すと、エラーページに遷移します。プロトタイプ詳細ページに戻るように修正しましょう。

**ユーザー詳細機能**

- [x] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移すること**
以下の動画の通り、クリックしたユーザー名と、遷移先のユーザー詳細ページが一致していません。一致するように修正しましょう。

https://github.com/user-attachments/assets/f807c54b-6fb3-439b-a400-822c516b5e4f

- [x] **ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページには、そのユーザーの詳細情報（名前・プロフィール・所属・役職）と、そのユーザーが投稿したプロトタイプが表示されていること**
以下画像の赤枠部分に、正しいユーザー名が表示されるように修正しましょう。
<img width="1119" alt="スクリーンショット 2024-11-29 16 26 06" src="https://github.com/user-attachments/assets/aa387c7f-9c5d-46bd-93ac-55754ce5f8d4">


修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう。
修正内容が反映されていることが確認できましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by Taka41802** [comment]
修正しました！

**Comment by TakashiKozuma** [comment]
ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです。　
おめでとうございます。

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう。
